# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{did_csv_builder}
  s.version = "0.1.4.beta2"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Tom Stuart}]
  s.date = %q{2011-07-29}
  s.description = %q{CSV template Rails plugin}
  s.email = %q{didier@nocoffee.fr}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "lib/csv_builder.rb",
     "lib/csv_builder/action_controller.rb",
     "lib/csv_builder/template_handler/base.rb"
  ]
  s.homepage = %q{https://github.com/did/csv_builder}
  s.rdoc_options = [%q{--charset=UTF-8}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{CSV template Rails plugin}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

